name: Documentation Update

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate Documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Generate Documentation
        run: php ./makeDocs.php

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          directory: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Auto-updated documentation"
