name: Documentation Update

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate Documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Dev Dependencies
        run: composer update

      - name: Generate Documentation
        run: php ./makeDocs.php

      - name: Commit & Push to Wiki
        run:  |
          cd docs
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add *.md
          git commit -m "Auto-Update Documentation" || echo "No changes to commit"
          git push
          cd ..

      - name: Commit & Push Submodule Update
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Auto-updated documentation"
