name: Unit Tests

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.2', '8.4' ]

    name: PHP ${{ matrix.php-versions }} tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          ini-values: max_execution_time=15
        env:
          update: true

      - name: Composer
        run: composer update

      - name: Tests (PHP 7)
        env:
          XDEBUG_MODE: coverage
        run: ./vendor/bin/phpunit -c phpunit.7.xml --coverage-clover clover.xml
        if: contains(matrix.php-versions, '7.')

      - name: Tests (PHP 8)
        env:
          XDEBUG_MODE: coverage
        run: ./vendor/bin/phpunit --coverage-clover clover.xml
        if: contains(matrix.php-versions, '8.')

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php-versions }}
        run: ./vendor/bin/php-coveralls -x clover.xml -o coverage.json -v

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Close Coveralls Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_ENDPOINT: https://coveralls.io
        run: curl -k $COVERALLS_ENDPOINT/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$GITHUB_RUN_ID&payload[status]=done"