name: Unit_Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['5.5', '5.6', '7.0', '7.2', '7.3', '7.4', '8.0']

        name: PHP ${{ matrix.php-versions }} tests
        steps:
            # basically git clone
            -   name: Checkout
                uses: actions/checkout@v2
            
            -   name: Composer
                uses: php-actions/composer@v5
            
            -   name: Tests
                uses: php-actions/phpunit@v2
                with:
                    configuration: phpunit.xml
                    php_version: ${{ matrix.php-versions }}
                    php_extensions: xdebug
