name: Unit_Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

        name: PHP ${{ matrix.php-versions }} tests
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            
            -   name: Composer
                uses: php-actions/composer@v5
                with:
                    php_version: ${{ matrix.php-versions }}
            
            -   name: Tests
                env:
                    XDEBUG_MODE: coverage
                run: ./vendor/bin/phpunit --coverage-clover clover.xml

            -   name: Upload coverage results to Coveralls
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_GITHUB_TOKEN }}
                    COVERALLS_PARALLEL: true
                    COVERALLS_FLAG_NAME: ${{ matrix.php-versions }}
                run: ./vendor/bin/php-coveralls -x clover.xml -v
